/// <reference lib="webworker" />
// Service worker — generated by Serwist at build time. The file
// itself is processed by `@serwist/next` (see `next.config.mjs`)
// which compiles it to `public/sw.js` and injects the build-time
// precache manifest into `__SW_MANIFEST`. The browser registers
// `/sw.js` automatically via the runtime that Serwist ships with.
//
// Caching philosophy:
//
//   - **App shell** (HTML, CSS, JS, fonts): precached at install
//     time. Boot is instant offline.
//   - **Catalog reads** (Server Actions GET-equivalents): not yet
//     cached here — they're already fast (<100ms) and changing
//     them requires waiting for the user's session to be valid
//     server-side. Re-evaluate in a follow-up if offline reads
//     are wanted.
//   - **Media thumbnails** (`/api/media/*`): CacheFirst with a 30-
//     day expiration and a 200-entry cap. Once you've viewed a
//     case, its image is yours forever (or until cap eviction).
//   - **Media videos**: NetworkOnly. Big files we don't want
//     filling the cache.
//   - **External (Clerk, Sentry, fonts)**: NetworkOnly + the SW's
//     own queue retries on failure. We don't want stale auth
//     state from the cache.
//
// Update flow: when a new SW activates, `skipWaiting + clientsClaim`
// pushes it live; pages reload via the `controllerchange` event
// hooked up in the layout. The user sees a one-line "Hay una
// versión nueva — recargá" toast (see `useServiceWorker.ts`).

import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { CacheFirst, ExpirationPlugin, NetworkOnly, Serwist } from "serwist";

// The Serwist toolbox installs `__SW_MANIFEST` on the global scope at
// build time. Augmenting the type so TS doesn't complain.
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

// Custom rules layered ON TOP of Serwist's `defaultCache`. The
// default already covers HTML / static / Google Fonts / RSC reads
// with sensible strategies; we only add the project-specific paths.
const customRuntimeCaching = [
  // Media images — the heaviest payload after the first paint.
  // CacheFirst means once the file is fetched, every subsequent
  // request short-circuits to the cache without hitting the
  // network. Combined with the optimizer's stable URLs this is a
  // huge perf + bandwidth win, and offline-friendly as a bonus.
  {
    matcher: ({ url, request }: { url: URL; request: Request }) => {
      if (request.destination !== "image") return false;
      // /api/media/<id>.<ext> — our blob route. Skip videos, they
      // have a separate rule below.
      if (!/^\/api\/media\//.test(url.pathname)) return false;
      return !/\.(mp4|webm|mov|m4v)(\?|$)/i.test(url.pathname);
    },
    handler: new CacheFirst({
      cacheName: "pocus-media-images",
      plugins: [
        new ExpirationPlugin({
          maxEntries: 200,
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
          purgeOnQuotaError: true,
        }),
      ],
    }),
  },
  // Media videos — too big to cache responsibly. Force network.
  {
    matcher: ({ url }: { url: URL }) =>
      /^\/api\/media\//.test(url.pathname) && /\.(mp4|webm|mov|m4v)(\?|$)/i.test(url.pathname),
    handler: new NetworkOnly(),
  },
  // Server Action POSTs — never cache (they mutate state).
  {
    matcher: ({ request }: { request: Request }) => request.method === "POST",
    handler: new NetworkOnly(),
  },
];

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [...customRuntimeCaching, ...defaultCache],
});

serwist.addEventListeners();
