/// <reference lib="webworker" />
// Service worker — generated by Serwist at build time. The file
// itself is processed by `@serwist/next` (see `next.config.mjs`)
// which compiles it to `public/sw.js` and injects the build-time
// precache manifest into `__SW_MANIFEST`. The browser registers
// `/sw.js` automatically via the runtime that Serwist ships with.
//
// Caching philosophy:
//
//   - **App shell** (HTML, CSS, JS, fonts): precached at install
//     time. Boot is instant offline.
//   - **Catalog reads** (Server Actions GET-equivalents): not yet
//     cached here — they're already fast (<100ms) and changing
//     them requires waiting for the user's session to be valid
//     server-side. Re-evaluate in a follow-up if offline reads
//     are wanted.
//   - **Media thumbnails** (`/api/media/*`): CacheFirst with a 30-
//     day expiration and a 200-entry cap. Once you've viewed a
//     case, its image is yours forever (or until cap eviction).
//   - **Next.js optimizer images** (`/_next/image*`): CacheFirst
//     too — the URLs are content-addressable (the params encode
//     the source + width + quality so a different render is a
//     different URL).
//   - **Cases corpus JSON** (`/data/imported-cases.json`): SWR
//     so the user always sees fresh data when online but the
//     catalog still loads from cache when the network blips.
//   - **Media videos**: NetworkOnly. Big files we don't want
//     filling the cache.
//   - **External (Clerk, Sentry, fonts)**: NetworkOnly + the SW's
//     own queue retries on failure. We don't want stale auth
//     state from the cache.
//
// Update flow: when a new SW activates, `skipWaiting + clientsClaim`
// pushes it live; pages reload via the `controllerchange` event
// hooked up in the layout. The user sees a one-line "Hay una
// versión nueva — recargá" toast (see `useServiceWorker.ts`).

import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { CacheFirst, ExpirationPlugin, NetworkOnly, Serwist, StaleWhileRevalidate } from "serwist";

// The Serwist toolbox installs `__SW_MANIFEST` on the global scope at
// build time. Augmenting the type so TS doesn't complain.
declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

// Custom rules layered ON TOP of Serwist's `defaultCache`. The
// default already covers HTML / static / Google Fonts / RSC reads
// with sensible strategies; we only add the project-specific paths.
const customRuntimeCaching = [
  // Media images — the heaviest payload after the first paint.
  // CacheFirst means once the file is fetched, every subsequent
  // request short-circuits to the cache without hitting the
  // network. Combined with the optimizer's stable URLs this is a
  // huge perf + bandwidth win, and offline-friendly as a bonus.
  {
    matcher: ({ url, request }: { url: URL; request: Request }) => {
      if (request.destination !== "image") return false;
      // /api/media/<id>.<ext> — our blob route. Skip videos, they
      // have a separate rule below.
      if (!/^\/api\/media\//.test(url.pathname)) return false;
      return !/\.(mp4|webm|mov|m4v)(\?|$)/i.test(url.pathname);
    },
    handler: new CacheFirst({
      cacheName: "pocus-media-images",
      plugins: [
        new ExpirationPlugin({
          maxEntries: 200,
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
          purgeOnQuotaError: true,
        }),
      ],
    }),
  },
  // Media videos — too big to cache responsibly. Force network.
  {
    matcher: ({ url }: { url: URL }) =>
      /^\/api\/media\//.test(url.pathname) && /\.(mp4|webm|mov|m4v)(\?|$)/i.test(url.pathname),
    handler: new NetworkOnly(),
  },
  // Next.js Image optimizer route. URLs are content-addressable
  // (parameters encode the source URL + width + quality, so a
  // different render lives at a different URL); CacheFirst is
  // safe and dramatically faster on repeat catalog visits.
  // 7-day TTL because the actual asset behind the optimizer
  // could be replaced (admin re-uploads media for a case); a
  // shorter TTL than the source-blob cache (30 days) accepts a
  // small lag in exchange for not serving a stale optimized
  // variant for a month.
  {
    matcher: ({ url }: { url: URL }) => /^\/_next\/image/.test(url.pathname),
    handler: new CacheFirst({
      cacheName: "pocus-next-images",
      plugins: [
        new ExpirationPlugin({
          maxEntries: 300,
          maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
          purgeOnQuotaError: true,
        }),
      ],
    }),
  },
  // Cases corpus JSON. StaleWhileRevalidate gives the best of
  // both worlds: instant load from cache (the corpus is always
  // ready, even before the network responds) AND a background
  // revalidate so updates land on the next interaction. If the
  // network is down, the cached copy is the answer. The corpus
  // is ~133 KB minified — well under the cache budget. We cache
  // both the main file and the audit sidecar with the same rule.
  {
    matcher: ({ url }: { url: URL }) => /^\/data\/.*\.json$/.test(url.pathname),
    handler: new StaleWhileRevalidate({
      cacheName: "pocus-data",
      plugins: [
        new ExpirationPlugin({
          maxEntries: 10,
          maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
          purgeOnQuotaError: true,
        }),
      ],
    }),
  },
  // Server Action POSTs — never cache (they mutate state).
  {
    matcher: ({ request }: { request: Request }) => request.method === "POST",
    handler: new NetworkOnly(),
  },
];

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [...customRuntimeCaching, ...defaultCache],
});

serwist.addEventListeners();

// ============================================================
// Selective offline cache for media videos
// ============================================================
//
// Videos are intentionally NetworkOnly in the runtime rules above
// (auto-caching every viewed clip would fill the storage budget in
// minutes and is rarely the user's intent). Instead, this section
// opts a SPECIFIC video into a hand-managed cache when the user
// clicks the modal's "Guardar offline" toggle.
//
// Wire:
//   1. The client posts `{ type: "offline:add" | "offline:remove" |
//      "offline:list" | "offline:purge-all", url }` via
//      `navigator.serviceWorker.controller.postMessage`.
//   2. This SW handles the message, mutates the
//      `pocus-offline-media` Cache, and replies with the result so
//      the client can update its state and toast.
//   3. A custom `fetch` listener (registered BEFORE Serwist takes
//      over) checks `pocus-offline-media` for the request first;
//      hit = serve from cache (works offline); miss = fall through
//      so Serwist's NetworkOnly rule for videos handles it.
//
// LRU on quota error: the `add` handler tries `cache.put`; if it
// throws QuotaExceededError, we evict the OLDEST entry (the one
// added longest ago, via the per-URL timestamp we keep in
// IndexedDB) and retry once. If the second `put` also fails the
// client gets an error reply and can show a "no space" toast.

const OFFLINE_CACHE = "pocus-offline-media";
const OFFLINE_DB = "pocus-offline-meta";
const OFFLINE_DB_STORE = "timestamps";

/** Match the same video-URL pattern the NetworkOnly rule above uses. */
function isOfflineMediaUrl(url: URL): boolean {
  return /^\/api\/media\//.test(url.pathname) && /\.(mp4|webm|mov|m4v)(\?|$)/i.test(url.pathname);
}

/** Open the metadata DB once; the SW's lifetime is short and the
 *  open cost is tiny, but the helper keeps call-sites clean. */
function openMetaDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(OFFLINE_DB, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(OFFLINE_DB_STORE)) {
        db.createObjectStore(OFFLINE_DB_STORE);
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function setTimestamp(url: string): Promise<void> {
  const db = await openMetaDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(OFFLINE_DB_STORE, "readwrite");
    tx.objectStore(OFFLINE_DB_STORE).put(Date.now(), url);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
  db.close();
}

async function deleteTimestamp(url: string): Promise<void> {
  const db = await openMetaDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(OFFLINE_DB_STORE, "readwrite");
    tx.objectStore(OFFLINE_DB_STORE).delete(url);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
  db.close();
}

/** Walks the timestamp store and returns the URL added longest
 *  ago — the LRU eviction target when storage hits quota. */
async function oldestUrl(): Promise<string | null> {
  const db = await openMetaDb();
  return new Promise<string | null>((resolve, reject) => {
    const tx = db.transaction(OFFLINE_DB_STORE, "readonly");
    const store = tx.objectStore(OFFLINE_DB_STORE);
    const cursorReq = store.openCursor();
    let oldest: { url: string; ts: number } | null = null;
    cursorReq.onsuccess = () => {
      const cursor = cursorReq.result;
      if (!cursor) {
        db.close();
        resolve(oldest?.url ?? null);
        return;
      }
      const ts = cursor.value as number;
      const url = cursor.key as string;
      if (!oldest || ts < oldest.ts) oldest = { url, ts };
      cursor.continue();
    };
    cursorReq.onerror = () => {
      db.close();
      reject(cursorReq.error);
    };
  });
}

/** Fetch + store with LRU retry. Returns `{ evicted: string[] }`
 *  listing any URLs the client should drop from its local state
 *  (they were evicted to make room for the new add). */
async function addToOfflineCache(url: string): Promise<{ evicted: string[] }> {
  const cache = await caches.open(OFFLINE_CACHE);
  const response = await fetch(url);
  if (!response.ok) throw new Error(`fetch HTTP ${response.status}`);
  const evicted: string[] = [];
  // Retry on QuotaExceededError up to N times — each retry frees the
  // oldest entry. Bounded so a degenerate storage situation can't
  // loop forever.
  for (let attempt = 0; attempt < 6; attempt++) {
    try {
      // Clone needed because put consumes the response body.
      await cache.put(url, response.clone());
      await setTimestamp(url);
      return { evicted };
    } catch (err) {
      const name = (err as { name?: string })?.name;
      if (name !== "QuotaExceededError") throw err;
      const victim = await oldestUrl();
      if (!victim) throw err; // nothing left to evict, but still no room
      await cache.delete(victim);
      await deleteTimestamp(victim);
      evicted.push(victim);
    }
  }
  throw new Error("quota exceeded after retries");
}

async function removeFromOfflineCache(url: string): Promise<void> {
  const cache = await caches.open(OFFLINE_CACHE);
  await cache.delete(url);
  await deleteTimestamp(url);
}

async function listOfflineCache(): Promise<string[]> {
  const cache = await caches.open(OFFLINE_CACHE);
  const reqs = await cache.keys();
  // Strip the origin so the client can match against the same
  // relative URLs it stores in localStorage — origins differ
  // between dev, preview, and production deploys.
  return reqs.map((r) => new URL(r.url).pathname + new URL(r.url).search);
}

async function purgeOfflineCache(): Promise<void> {
  await caches.delete(OFFLINE_CACHE);
  // Wipe the timestamp store too.
  const db = await openMetaDb();
  await new Promise<void>((resolve, reject) => {
    const tx = db.transaction(OFFLINE_DB_STORE, "readwrite");
    tx.objectStore(OFFLINE_DB_STORE).clear();
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
  db.close();
}

// Cache-first read path. Registered as its own `fetch` listener
// BEFORE Serwist's runtime caching kicks in (event listeners fire
// in registration order; first to call `respondWith` wins). For
// non-video paths we return without responding, letting Serwist's
// own listener (registered by `serwist.addEventListeners()` above)
// handle the request normally.
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (!isOfflineMediaUrl(url)) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(OFFLINE_CACHE);
      const cached = await cache.match(event.request);
      if (cached) return cached;
      // Not in the offline cache — fall through to network. The
      // existing NetworkOnly rule for video URLs in the runtime
      // caching above would handle this too, but it's already
      // bypassed by the time we get here (we called respondWith).
      // So fetch directly. Errors propagate naturally and the
      // browser shows its usual "video unavailable" affordance.
      return fetch(event.request);
    })(),
  );
});

self.addEventListener("message", (event) => {
  const data = event.data;
  if (!data || typeof data !== "object" || typeof data.type !== "string") return;
  // Reply via the originating port if `postMessage` was sent with
  // a MessageChannel, otherwise via `event.source` (the client).
  const reply = (msg: object) => {
    if (event.ports && event.ports[0]) {
      event.ports[0].postMessage(msg);
    } else if (event.source && "postMessage" in event.source) {
      (event.source as Client).postMessage(msg);
    }
  };
  if (data.type === "offline:add" && typeof data.url === "string") {
    const url = data.url;
    event.waitUntil(
      (async () => {
        try {
          const { evicted } = await addToOfflineCache(url);
          reply({ type: "offline:added", url, evicted });
        } catch (err) {
          reply({
            type: "offline:error",
            url,
            message: (err as Error)?.message ?? "fetch failed",
          });
        }
      })(),
    );
  } else if (data.type === "offline:remove" && typeof data.url === "string") {
    const url = data.url;
    event.waitUntil(
      (async () => {
        try {
          await removeFromOfflineCache(url);
          reply({ type: "offline:removed", url });
        } catch (err) {
          reply({
            type: "offline:error",
            url,
            message: (err as Error)?.message ?? "evict failed",
          });
        }
      })(),
    );
  } else if (data.type === "offline:list") {
    event.waitUntil(
      (async () => {
        try {
          const urls = await listOfflineCache();
          reply({ type: "offline:list-result", urls });
        } catch (err) {
          reply({
            type: "offline:error",
            url: "",
            message: (err as Error)?.message ?? "list failed",
          });
        }
      })(),
    );
  } else if (data.type === "offline:purge-all") {
    event.waitUntil(
      (async () => {
        try {
          await purgeOfflineCache();
          reply({ type: "offline:purged" });
        } catch (err) {
          reply({
            type: "offline:error",
            url: "",
            message: (err as Error)?.message ?? "purge failed",
          });
        }
      })(),
    );
  }
});
