import type { CaseRecord, Category, Section } from "./types";

export const SECTIONS: Section[] = [
  { id: "atlas", label: "Atlas POCUS", sub: "Imágenes y videos ecográficos por tema" },
  { id: "ecg", label: "ECG", sub: "Electrocardiogramas con interpretación" },
  { id: "cases", label: "Casos clínicos", sub: "Historias completas con razonamiento" },
  { id: "info", label: "Infografías", sub: "Algoritmos, protocolos y referencias visuales" },
];

export const CATEGORIES: Category[] = [
  { id: "cardiac", label: "Cardíaco", count: 0 },
  { id: "lung", label: "Pulmonar", count: 0 },
  { id: "abdominal", label: "Abdominal", count: 0 },
  { id: "fast", label: "FAST / Trauma", count: 0 },
  { id: "vascular", label: "Vascular", count: 0 },
  { id: "ob", label: "Obstétrico", count: 0 },
  { id: "ms", label: "Musculoesquelético", count: 0 },
  { id: "proc", label: "Procedimientos", count: 0 },
];

export const COMMON_TAGS = [
  "B-líneas",
  "Derrame pleural",
  "Neumotórax",
  "Consolidación",
  "Tamponade",
  "VI dilatado",
  "Disfunción VD",
  "FE reducida",
  "Pericarditis",
  "Líquido libre",
  "Hidronefrosis",
  "Colelitiasis",
  "Apendicitis",
  "TVP",
  "AAA",
  "Embarazo ectópico",
  "Latido fetal",
  "Bloqueo nervioso",
  "Acceso venoso",
  "Paracentesis",
  "Normal",
  "Patológico",
  "Pediátrico",
  "Crítico",
];

export const SEED_CASES: CaseRecord[] = [
  {
    id: "c001",
    section: "atlas",
    title: "B-líneas confluentes en edema pulmonar agudo",
    category: "lung",
    tags: ["B-líneas", "Patológico", "Crítico"],
    modality: "Sonda lineal · 5 MHz",
    loop: "blines",
    author: "Dra. M. Aguirre",
    role: "Medicina de Emergencia",
    date: "2026-04-18",
    findings:
      "Múltiples líneas B verticales que parten de la línea pleural, confluentes, bilaterales en zonas anteriores y laterales.",
    diagnosis: "Edema pulmonar cardiogénico",
    summary:
      "Paciente de 72 años con disnea súbita. La presencia de >3 líneas B por campo en al menos 2 zonas bilateralmente confirma síndrome intersticial.",
    featured: true,
  },
  {
    id: "c002",
    section: "atlas",
    title: "Derrame pericárdico con signos de tamponade",
    category: "cardiac",
    tags: ["Tamponade", "Patológico", "Crítico"],
    modality: "Sonda phased array · subcostal",
    loop: "tamponade",
    author: "Dr. J. Soriano",
    role: "Cuidados Intensivos",
    date: "2026-04-15",
    findings:
      "Derrame pericárdico circunferencial moderado con colapso diastólico de aurícula derecha y plétora de VCI sin variación respiratoria.",
    diagnosis: "Tamponade cardíaco",
    summary:
      "Hipotensión refractaria post-cirugía torácica. Hallazgo en POCUS llevó a pericardiocentesis emergente con resolución del cuadro.",
    featured: true,
  },
  {
    id: "c003",
    section: "atlas",
    title: "Líquido libre en bolsa de Morrison",
    category: "fast",
    tags: ["Líquido libre", "Patológico"],
    modality: "Sonda curvilínea · RUQ",
    loop: "morrison",
    author: "Dra. P. Linares",
    role: "Cirugía de Trauma",
    date: "2026-04-12",
    findings:
      "Banda anecoica entre hígado y riñón derecho, mayor a 5mm, en paciente politraumatizado.",
    diagnosis: "FAST positivo",
    summary:
      "Trauma abdominal cerrado. FAST positivo en RUQ indicó laparotomía urgente; hallazgo de laceración esplénica.",
  },
  {
    id: "c004",
    section: "atlas",
    title: "Deslizamiento pleural normal — modo M (signo de la orilla)",
    category: "lung",
    tags: ["Normal"],
    modality: "Sonda lineal · modo M",
    loop: "seashore",
    author: "Dr. F. Quiroga",
    role: "Medicina Interna",
    date: "2026-04-10",
    findings:
      "Patrón típico de 'orilla de mar' en modo M: líneas paralelas superficiales y patrón granular profundo.",
    diagnosis: "Pleura normal — descarta neumotórax",
    summary:
      "Aprende a reconocer el patrón normal antes de identificar el patológico. Referencia para descartar neumotórax con alta sensibilidad.",
  },
  {
    id: "c005",
    section: "atlas",
    title: "Vena yugular interna — acceso guiado",
    category: "proc",
    tags: ["Acceso venoso", "Normal"],
    modality: "Sonda lineal · transversal",
    loop: "ijv",
    author: "Dra. C. Méndez",
    role: "Anestesiología",
    date: "2026-04-08",
    findings:
      "Vena yugular interna compresible, anterolateral a carótida. Aguja visualizada en plano corto durante punción.",
    diagnosis: "Cateterización venosa central exitosa",
    summary:
      "Técnica out-of-plane en tiempo real. Reducción demostrada de complicaciones vs técnica anatómica ciega.",
  },
  {
    id: "c006",
    section: "atlas",
    title: "Trombosis venosa profunda femoral",
    category: "vascular",
    tags: ["TVP", "Patológico"],
    modality: "Sonda lineal · compresión",
    loop: "dvt",
    author: "Dr. A. Restrepo",
    role: "Medicina de Emergencia",
    date: "2026-04-05",
    findings:
      "Vena femoral común no compresible, con material ecogénico intraluminal. Pérdida de fasicidad respiratoria.",
    diagnosis: "TVP femoral aguda",
    summary:
      "Protocolo de 2 puntos: femoral común y poplítea. La no-compresibilidad es el hallazgo cardinal.",
  },
  {
    id: "c007",
    section: "atlas",
    title: "Hidronefrosis grado III",
    category: "abdominal",
    tags: ["Hidronefrosis", "Patológico"],
    modality: "Sonda curvilínea",
    loop: "hydro",
    author: "Dra. L. Vargas",
    role: "Urología",
    date: "2026-04-02",
    findings:
      "Dilatación severa del sistema colector renal con adelgazamiento del parénquima. Pelvis y cálices marcadamente dilatados.",
    diagnosis: "Hidronefrosis grado III por litiasis ureteral",
    summary:
      "Cólico renoureteral con dolor intenso. POCUS evita demora del diagnóstico mientras se gestiona TC.",
  },
  {
    id: "c008",
    section: "atlas",
    title: "Saco gestacional intrauterino con polo embrionario",
    category: "ob",
    tags: ["Latido fetal", "Normal"],
    modality: "Sonda endocavitaria",
    loop: "ob",
    author: "Dra. R. Inostroza",
    role: "Ginecología",
    date: "2026-03-30",
    findings:
      "Saco gestacional intrauterino con saco vitelino y polo embrionario de 7mm. Actividad cardíaca fetal presente.",
    diagnosis: "Embarazo intrauterino viable de 6+3 semanas",
    summary:
      "Confirmación de embarazo intrauterino descarta razonablemente ectópico en paciente sintomática.",
  },
  {
    id: "c009",
    section: "atlas",
    title: "Función ventricular izquierda severamente reducida",
    category: "cardiac",
    tags: ["FE reducida", "VI dilatado", "Patológico"],
    modality: "Sonda phased array · paraesternal eje largo",
    loop: "lvfunction",
    author: "Dr. J. Soriano",
    role: "Cuidados Intensivos",
    date: "2026-03-28",
    findings:
      "VI dilatado con hipocinesia global severa. Engrosamiento miocárdico mínimo. FE estimada por eyeballing < 20%.",
    diagnosis: "Miocardiopatía dilatada con disfunción sistólica severa",
    summary:
      "Shock cardiogénico de novo. POCUS guió terapia inotrópica precoz mientras se obtenía ecocardiograma formal.",
    featured: true,
  },
  {
    id: "c010",
    section: "atlas",
    title: "Aneurisma aórtico abdominal infrarrenal",
    category: "vascular",
    tags: ["AAA", "Patológico", "Crítico"],
    modality: "Sonda curvilínea · transversal",
    loop: "aaa",
    author: "Dra. P. Linares",
    role: "Cirugía Vascular",
    date: "2026-03-25",
    findings:
      "Aorta abdominal con diámetro AP de 6.2 cm a nivel infrarrenal. Trombo mural ecogénico parcial.",
    diagnosis: "AAA fusiforme grande, no roto",
    summary:
      "Dolor abdominal y lumbar en paciente de 78 años. POCUS al pie de cama identificó el aneurisma en <2 minutos.",
  },
  {
    id: "c011",
    section: "atlas",
    title: "Consolidación lobar con broncograma aéreo dinámico",
    category: "lung",
    tags: ["Consolidación", "Patológico"],
    modality: "Sonda curvilínea",
    loop: "consolidation",
    author: "Dra. M. Aguirre",
    role: "Medicina de Emergencia",
    date: "2026-03-22",
    findings:
      "Tejido pulmonar con ecogenicidad similar a hígado ('hepatización'), broncogramas aéreos puntiformes y lineales con movimiento centrífugo.",
    diagnosis: "Neumonía lobar",
    summary:
      "Diferencial con atelectasia: el broncograma aéreo dinámico (movimiento con respiración) favorece neumonía.",
  },
  {
    id: "c012",
    section: "atlas",
    title: "Colelitiasis con sombra acústica posterior",
    category: "abdominal",
    tags: ["Colelitiasis", "Patológico"],
    modality: "Sonda curvilínea · RUQ",
    loop: "gallstone",
    author: "Dr. F. Quiroga",
    role: "Medicina Interna",
    date: "2026-03-19",
    findings:
      "Imagen hiperecogénica intravesicular móvil con sombra acústica posterior limpia. Pared vesicular no engrosada.",
    diagnosis: "Colelitiasis sin colecistitis",
    summary:
      "Triada clásica: estructura hiperecogénica + sombra acústica + movilidad con cambios posicionales.",
  },

  // ----- ECG -----
  {
    id: "ecg001",
    section: "ecg",
    title: "STEMI inferior con elevación en cara inferior",
    category: "cardiac",
    tags: ["STEMI", "Crítico", "Patológico"],
    modality: "ECG 12 derivaciones",
    loop: "ecg-stemi",
    author: "Dr. J. Soriano",
    role: "Cardiología",
    date: "2026-04-20",
    findings:
      "Elevación del ST > 2mm en DII, DIII, aVF. Depresión recíproca en aVL y DI. Onda Q patológica incipiente.",
    diagnosis: "Infarto agudo de miocardio inferior",
    summary:
      "Varón de 58 años con dolor precordial opresivo de 40 min. ECG diagnóstico — activación de hemodinamia.",
    featured: true,
  },
  {
    id: "ecg002",
    section: "ecg",
    title: "Fibrilación auricular con respuesta ventricular rápida",
    category: "cardiac",
    tags: ["FA", "Patológico"],
    modality: "ECG 12 derivaciones",
    loop: "ecg-afib",
    author: "Dra. M. Aguirre",
    role: "Medicina de Emergencia",
    date: "2026-04-14",
    findings:
      "Ritmo irregularmente irregular, ausencia de ondas P, ondas f de fibrilación. FC 142 lpm.",
    diagnosis: "Fibrilación auricular con respuesta ventricular rápida",
    summary:
      "Palpitaciones de inicio súbito hace 2h. Inestable hemodinámicamente — cardioversión eléctrica.",
  },
  {
    id: "ecg003",
    section: "ecg",
    title: "Bloqueo AV completo (3er grado)",
    category: "cardiac",
    tags: ["Bloqueo AV", "Crítico", "Patológico"],
    modality: "ECG 12 derivaciones",
    loop: "ecg-block",
    author: "Dr. F. Quiroga",
    role: "Cardiología",
    date: "2026-04-08",
    findings:
      "Disociación auriculoventricular completa. Frecuencia auricular 80, ventricular 38. QRS ancho de escape.",
    diagnosis: "Bloqueo AV de tercer grado",
    summary: "Síncope recurrente. Marcapaso transitorio en urgencia, definitivo en 24h.",
  },

  // ----- CASOS CLÍNICOS -----
  {
    id: "case001",
    section: "cases",
    title: "Disnea súbita en mujer de 34 años post-parto",
    category: "lung",
    tags: ["TEP", "Crítico", "Patológico"],
    modality: "Caso clínico integrado",
    loop: "blines",
    author: "Dra. P. Linares",
    role: "Medicina de Emergencia",
    date: "2026-04-22",
    findings:
      "POCUS: dilatación VD, signo de McConnell, septum aplanado. AngioTC confirma TEP bilateral.",
    diagnosis: "Tromboembolismo pulmonar masivo",
    summary:
      "Mujer de 34a, 5 días postparto, disnea súbita y sat 88%. POCUS al pie de cama orientó diagnóstico antes del TC. Anticoagulación inmediata + trombólisis.",
    featured: true,
  },
  {
    id: "case002",
    section: "cases",
    title: "Shock indiferenciado en paciente de 72 años",
    category: "cardiac",
    tags: ["Shock", "Protocolo RUSH", "Crítico"],
    modality: "Caso clínico integrado",
    loop: "lvfunction",
    author: "Dr. J. Soriano",
    role: "Cuidados Intensivos",
    date: "2026-04-16",
    findings:
      "RUSH: corazón hiperdinámico, VCI colapsable, líneas A bilaterales, FAST negativo, aorta normal. Sugiere shock distributivo.",
    diagnosis: "Shock séptico de origen urinario",
    summary:
      "Hipotensión sin causa clara. Protocolo RUSH dirigió la reanimación: volumen + noradrenalina + ATB de amplio espectro.",
  },
  {
    id: "case003",
    section: "cases",
    title: "Dolor abdominal agudo en hombre de 65 años",
    category: "abdominal",
    tags: ["AAA", "Crítico", "Patológico"],
    modality: "Caso clínico integrado",
    loop: "aaa",
    author: "Dra. P. Linares",
    role: "Cirugía Vascular",
    date: "2026-04-10",
    findings: "POCUS aorta: 6.4 cm con líquido libre periaórtico. Inestable hemodinámicamente.",
    diagnosis: "AAA roto",
    summary:
      "Hombre de 65a, dolor lumbar súbito, hipotensión. POCUS en <90 segundos cambió el destino: pabellón directo en lugar de TC.",
  },

  // ----- INFOGRAFÍAS -----
  {
    id: "info001",
    section: "info",
    title: "Protocolo BLUE: algoritmo de disnea aguda",
    category: "lung",
    tags: ["Protocolo", "BLUE", "Pulmonar"],
    modality: "Algoritmo visual",
    loop: "info-blue",
    author: "Equipo Taote",
    role: "Educación",
    date: "2026-04-23",
    findings:
      "Algoritmo paso a paso: A-líneas + sliding → descartar TEP. B-líneas → edema vs neumonía. PLAPS → derrame.",
    diagnosis: "Diagnóstico diferencial de disnea por POCUS",
    summary:
      "Protocolo BLUE de Lichtenstein adaptado en infografía visual. Imprime y pega en tu carro de paro.",
    featured: true,
  },
  {
    id: "info002",
    section: "info",
    title: "Protocolo RUSH: shock indiferenciado",
    category: "cardiac",
    tags: ["Protocolo", "RUSH", "Shock"],
    modality: "Algoritmo visual",
    loop: "info-rush",
    author: "Equipo Taote",
    role: "Educación",
    date: "2026-04-19",
    findings:
      "Pump (corazón), Tank (VCI + pulmón + abdomen), Pipes (aorta + venas). Cada compartimento sugiere etiología.",
    diagnosis: "Diagnóstico diferencial de shock por POCUS",
    summary:
      "El protocolo RUSH descompone la evaluación del shock en 3 pasos visuales. Referencia rápida con hallazgos clave por compartimento.",
  },
  {
    id: "info003",
    section: "info",
    title: "FAST extendido (E-FAST): los 8 puntos",
    category: "fast",
    tags: ["FAST", "Trauma", "Protocolo"],
    modality: "Algoritmo visual",
    loop: "info-fast",
    author: "Equipo Taote",
    role: "Educación",
    date: "2026-04-11",
    findings:
      "Subxifoideo, RUQ (Morrison), LUQ (esplenorenal), suprapúbico, +2 puntos torácicos por hemitórax.",
    diagnosis: "Mapa de exploración E-FAST",
    summary:
      "Mapa anatómico con orden de exploración recomendado. Tiempo objetivo: <3 minutos en trauma.",
  },
];
